### ISSUE TITLE
[Bug] java.lang.Throwable: Do not perform a synchronous refresh under read lock (causes deadlocks if there are events to fire). EDT=false

### ISSUE THREAD

**Issue by andreistanescu2** [Atwix/phpstorm-plugin-feedback#70] opened 2024-02-05 10:27 UTC
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.Throwable: Do not perform a synchronous refresh under read lock (causes deadlocks if there are events to fire). EDT=false
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.execute(RefreshQueueImpl.java:67)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.launch(RefreshSessionImpl.java:122)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.processEvents(RefreshQueueImpl.java:187)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.createAndFindChildWithEventFire(VirtualDirectoryImpl.java:310)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:87)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.refreshAndFindChild(VirtualDirectoryImpl.java:352)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.refreshAndFindFileByPath(VfsImplUtil.java:118)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByPath(LocalFileSystemBase.java:129)
	at com.intellij.openapi.vfs.VfsUtil.findFile(VfsUtil.java:204)
	at com.intellij.openapi.vfs.VfsUtil.findFile(VfsUtil.java:193)
	at com.atwix.magento.project.util.MagentoProjectUtil.getMagentoProjectRootVf(MagentoProjectUtil.java:78)
	at com.atwix.magento.feature.jsComponent.search.JsFileSearch.searchInLibs(JsFileSearch.kt:86)
	at com.atwix.magento.feature.jsComponent.search.JsFileSearch.search(JsFileSearch.kt:64)
	at com.atwix.magento.indexing.provider.JsComponentIndexProvider.resolveWidgetForPath(JsComponentIndexProvider.kt:152)
	at com.atwix.magento.indexing.provider.JsComponentIndexProvider.getWidgetImpls(JsComponentIndexProvider.kt:140)
	at com.atwix.magento.feature.jsComponent.reference.provider.WidgetForMageInitReferenceProvider.getReferencesByJsonStringLiteral(WidgetForMageInitReferenceProvider.kt:61)
	at com.atwix.magento.feature.jsComponent.reference.provider.WidgetForMageInitReferenceProvider.getReferencesByElement(WidgetForMageInitReferenceProvider.kt:35)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:184)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:165)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:144)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:44)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:42)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:35)
	at com.intellij.json.psi.impl.JsonLiteralMixin.getReferences(JsonLiteralMixin.java:19)
	at com.intellij.json.psi.impl.JsonLiteralImpl.getReferences(JsonLiteralImpl.java:13)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:37)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:25)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:29)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.lambda$execute$0(PsiSearchHelperImpl.java:1036)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:87)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:178)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:207)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:177)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.execute(PsiSearchHelperImpl.java:1032)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.processInReadAction(PsiSearchHelperImpl.java:817)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.processInReadAction(PsiSearchHelperImpl.java:808)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intell
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/02/05
 - Plugin version: 2023.5.3/L
 - PhpStorm version: 2023.3.3 (PS-233.14015.96)
 - OS version: Windows 11.0

**Comment by bohdan-harniuk** [comment] 2024-02-05 10:50
Thank you for reporting this issue. It has been marked as a duplicate of [Original Issue #68](https://github.com/Atwix/phpstorm-plugin-feedback/issues/68).

We appreciate your contribution, and the problem you've identified will be addressed within the context of the original issue.

Thank you for your understanding and your involvement in improving the project.

**Closed by bohdan-harniuk** 2024-02-05 10:50 UTC
