### ISSUE TITLE
[Bug] java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by alikhani97** [Atwix/phpstorm-plugin-feedback#60] opened 2024-01-01 20:28 UTC
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:809)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364)
	at com.intellij.execution.process.ProcessIOExecutorService.execute(ProcessIOExecutorService.java:31)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at com.intellij.openapi.vfs.DiskQueryRelay.lambda$accessDiskWithCheckCanceled$1(DiskQueryRelay.java:47)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.openapi.vfs.DiskQueryRelay.accessDiskWithCheckCanceled(DiskQueryRelay.java:47)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.getAttributes(LocalFileSystemBase.java:736)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl.getAttributes(LocalFileSystemImpl.java:300)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.isDirectory(LocalFileSystemBase.java:184)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:89)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.refreshAndFindChild(VirtualDirectoryImpl.java:352)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.refreshAndFindFileByPath(VfsImplUtil.java:118)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByPath(LocalFileSystemBase.java:129)
	at com.intellij.openapi.vfs.VfsUtil.findFile(VfsUtil.java:204)
	at com.intellij.openapi.vfs.VfsUtil.findFile(VfsUtil.java:193)
	at com.atwix.magento.feature.jsComponent.search.JsFileSearch.searchInLibs(JsFileSearch.kt:93)
	at com.atwix.magento.feature.jsComponent.search.JsFileSearch.search(JsFileSearch.kt:64)
	at com.atwix.magento.indexing.provider.JsComponentIndexProvider.resolveWidgetForPath(JsComponentIndexProvider.kt:152)
	at com.atwix.magento.indexing.provider.JsComponentIndexProvider.getWidgetImpls(JsComponentIndexProvider.kt:140)
	at com.atwix.magento.feature.jsComponent.reference.provider.WidgetForMageInitReferenceProvider.getReferencesByJsonStringLiteral(WidgetForMageInitReferenceProvider.kt:61)
	at com.atwix.magento.feature.jsComponent.reference.provider.WidgetForMageInitReferenceProvider.getReferencesByElement(WidgetForMageInitReferenceProvider.kt:35)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:184)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:165)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:144)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:44)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:42)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:35)
	at com.intellij.json.psi.impl.JsonLiteralMixin.getReferences(JsonLiteralMixin.java:19)
	at com.intellij.json.psi.impl.JsonLiteralImpl.getReferences(JsonLiteralImpl.java:13)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:58)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:33)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:50)
	at com.intellij.psi.impl.PsiElementBase.findReferenceAt(PsiElementBase.java:76)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:226)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:222)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:525)
	at org.intellij.plugins.intelliLang.inject.InjectLanguageAction.isAvailable(InjectLanguageAction.java:114)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:218)
	at com.intellij.codeInsight.
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/01/01
 - Plugin version: 2023.5.2/L
 - PhpStorm version: 2023.3.2 (PS-233.13135.108)
 - OS version: macOS 14.2.1

**Comment by bohdan-harniuk** [comment] 2024-03-14 09:03
Hello @alikhani97,

Thank you for taking the time to report this issue. We greatly appreciate your contribution to improving our project. 
We've thoroughly investigated the reported issue within our codebase but couldn't identify any root cause. It's highly probable that this error was triggered by PHPStorm and may be related to memory limits being exceeded. It's likely a temporary issue.

We're closing this ticket for now. However, if you encounter the problem again or have additional details to share, please don't hesitate to reopen it. We're here to help.

Best regards,

**Closed by bohdan-harniuk** 2024-03-14 09:03 UTC
