### ISSUE TITLE
[Bug] java.lang.Throwable: Stub index points to a file without PSI: file = file:///home/rakesh/projects/, file type = com.intellij.openapi.fileTypes.UnknownFileType@13450f82, indexed file type = null, indexing stamp info = null, used scope = Project and Libraries

### ISSUE THREAD

**Issue by RakeshJesadiya** [Atwix/phpstorm-plugin-feedback#42] opened 2023-10-05 09:12 UTC
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.Throwable: Stub index points to a file without PSI: file = file:///home/rakesh/projects/magento/vendor/magento/module-catalog-staging/Model, file type = com.intellij.openapi.fileTypes.UnknownFileType@13450f82, indexed file type = null, indexing stamp info = null, used scope = Project and Libraries
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:150)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:214)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:746)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1183)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1160)
	at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1241)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1236)
	at com.jetbrains.php.PhpIndexImpl.getInterfacesByFQN(PhpIndexImpl.java:1261)
	at com.jetbrains.php.lang.psi.elements.PhpClass.getDirectImplementedInterfaces(PhpClass.java:87)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getImplementedInterfaces(PhpClassImpl.java:571)
	at com.jetbrains.php.PhpClassHierarchyUtils.getImmediateParents(PhpClassHierarchyUtils.java:621)
	at com.atwix.magento.lang.php.util.PhpClassReaderUtil.getAllSuperTypes(PhpClassReaderUtil.kt:88)
	at com.atwix.magento.lang.php.util.PhpClassReaderUtil.getAllSuperTypes(PhpClassReaderUtil.kt:93)
	at com.atwix.magento.lang.php.util.PhpClassReaderUtil.getAllImplementedInterfaces(PhpClassReaderUtil.kt:64)
	at com.atwix.magento.lang.php.util.PhpClassReaderUtil.isClassImplementsInterface(PhpClassReaderUtil.kt:52)
	at com.atwix.magento.feature.controller.validator.ControllerValidator.validate(ControllerValidator.kt:20)
	at com.atwix.magento.feature.controller.hints.lineMarker.ControllerInfoLineMarkerProvider.getLineMarkerInfo(ControllerInfoLineMarkerProvider.kt:31)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:183)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectMarkers$2(LineMarkersPass.java:113)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectMarkers(LineMarkersPass.java:103)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/10/05
 - Plugin version: 2023.5.0/F
 - PhpStorm version: 2023.2.2 (PS-232.9921.55)
 - OS version: Linux 5.15.0-76-generic

**Comment by bohdan-harniuk** [comment] 2023-10-05 11:10
Hi @RakeshJesadiya,

Please, [invalidate caches](https://www.jetbrains.com/help/idea/invalidate-caches.html) and try to do the same steps one more time. It seems to be an internal problem with the PHPStorm caches. If it won't help, please provide the detailed steps how to reproduce this issue.

Regards,

**Comment by bohdan-harniuk** [comment] 2023-10-14 03:10
Hi @RakeshJesadiya,

As mentioned earlier, the problem is associated with PHPStorm's native indexes and should typically be resolved by [invalidating caches](https://www.jetbrains.com/help/idea/invalidate-caches.html). These issues are transient and occur sporadically. I am closing this matter as it does not pertain to our plugin. If you require further assistance, please feel free to reopen the issue after attempting [cache invalidation](https://www.jetbrains.com/help/idea/invalidate-caches.html).

Regards,

**Closed by bohdan-harniuk** 2023-10-14 03:10 UTC
Labels: PHPStorm
