### ISSUE TITLE
[Bug] java.lang.AssertionError: PSI can be created only for a file with LanguageFileType but actual is class com.intellij.openapi.fileTypes.impl.DetectedByContentFileType.

### ISSUE THREAD

**Issue by ioweb-gr** [Atwix/phpstorm-plugin-feedback#94] opened 2024-09-02 08:47 UTC
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.AssertionError: PSI can be created only for a file with LanguageFileType but actual is class com.intellij.openapi.fileTypes.impl.DetectedByContentFileType.
Please use a proper FileBasedIndexExtension#getInputFilter() implementation for the caller index
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:77)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:232)
	at com.atwix.magento.indexing.processor.TranslationIndex$getIndexer$1.map(TranslationIndex.kt:32)
	at com.atwix.magento.indexing.processor.TranslationIndex$getIndexer$1.map(TranslationIndex.kt:31)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:318)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:250)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:288)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:65)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:30)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1634)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1504)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$freezeFileTypeTemporarilyWithProvidedValueIn$15(FileTypeManagerImpl.java:738)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:734)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1457)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1431)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1374)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1746)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1740)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1763)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:846)
	at com.intellij.psi.stubs.StubIndexEx.processAllKeys(StubIndexEx.java:303)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:75)
	at com.intellij.psi.stubs.StubIndexEx.getAllKeys(StubIndexEx.java:291)
	at com.intellij.lang.javascript.psi.stubs.JSUsedRemoteModulesIndex.getUsedModules(JSUsedRemoteModulesIndex.java:33)
	at com.intellij.lang.javascript.modules.remote.JSRemoteModulesUsagesDetector.findAllUsedModules(JSRemoteModulesUsagesDetector.java:66)
	at com.intellij.lang.javascript.modules.remote.JSRemoteModulesUsagesDetector.computeUpdatedModulesSnapshot(JSRemoteModulesUsagesDetector.java:117)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:840)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:872)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:604)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:93)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:135)
	at com.intellij.openapi.progress.ut
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/09/02
 - Plugin version: 2024.2.0/L
 - PhpStorm version: 2024.2.1 (PS-242.21829.154)
 - OS version: Windows 11.0

**Comment by bohdan-harniuk** [comment] 2024-09-02 09:13
Hello @ioweb-gr ,

Thank you for bringing this issue to our attention. After reviewing the stack trace, it appears that the problem is related to PHPStorm's native indexing feature and seems to be a temporary issue.

At this time, no further steps are required on your part. However, if the issue recurs, we recommend performing a cache invalidation in PHPStorm, which typically resolves similar transient issues that can arise due to various factors, such as unexpected shutdowns or other external influences.

Please note that this concern is associated with PHPStorm's native behaviour and does not pertain to our plugin. As such, we're marking this matter as closed. If the issue persists or if you require further assistance related to our plugin, feel free to reopen this issue, and we'll be happy to assist you further.

Thank you for your understanding and cooperation.

Best regards,

**Comment by bohdan-harniuk** [comment] 2024-09-02 09:31
Could you please provide a few screenshots showing what is making PHPStorm unusable while using our plugin? Additionally, any extra steps to reproduce the issue would be greatly appreciated, as they will help us offer better support.

**Comment by ioweb-gr** [comment] 2024-09-02 09:33
Yeah I miscliked the issue on mobile :) I've uninstalled the extension to reinstall it again just in case and I'll post back once it's done loading all project data.

**Comment by ioweb-gr** [comment] 2024-09-02 09:45
It seems after uninstalling -> reindex then installing again -> reindex the errors are gone. 

Previously I couldn't navigate to functions or automatically generate properties from the constructor variables  for example when 
the error hit. 

is it possible there might have been some corruption in the system which caused this? I think we can close the issues until they re-occur. If they do I'll post back.

**Comment by bohdan-harniuk** [comment] 2024-09-02 09:51
Based on the stack trace in the issue description, the problem seems to be related to PHPStorm's native indexing. This issue can be ignored or resolved by performing a [cache invalidation](https://www.jetbrains.com/help/idea/invalidate-caches.html). While incomplete indexing may temporarily affect parts of PHPStorm or the plugin, it's not a major concern as cache invalidation typically resolves it.

If you need further assistance, feel free to re-open this issue or create a new one.

**Closed by bohdan-harniuk** 2024-09-02 09:51 UTC
Labels: PHPStorm
