### ISSUE TITLE
[Bug]    NewModuleConfigFileAction#update@ProjectViewPopup (com.atwix.magento.feature.module.action.NewModuleConfigFileAction), actionId=Atwix.ContextMenu.NewModuleConfigFileAction, text='Magento 2 Configuration File'

### ISSUE THREAD

**Issue by mucan54** [Atwix/phpstorm-plugin-feedback#41] opened 2023-10-02 13:51 UTC
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
*** exception class was changed or removed

   NewModuleConfigFileAction#update@ProjectViewPopup (com.atwix.magento.feature.module.action.NewModuleConfigFileAction), actionId=Atwix.ContextMenu.NewModuleConfigFileAction, text='Magento 2 Configuration File'
   
   java.lang.RuntimeException: com.intellij.util.io.CorruptedException: PersistentEnumerator storage corrupted /Users/can/Library/Caches/JetBrains/PhpStorm2023.2/caches/names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.lambda$static$0(FSRecordsImpl.java:96)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.handleError(FSRecordsImpl.java:1172)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.getNameByNameId(FSRecordsImpl.java:818)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getNameByNameId(FSRecords.java:316)
	at com.intellij.openapi.vfs.newvfs.persistent.FileNameCache.getVFileName(FileNameCache.java:148)
	at com.intellij.openapi.vfs.newvfs.persistent.FileNameCache.getVFileName(FileNameCache.java:157)
	at com.intellij.openapi.vfs.newvfs.impl.VfsData.getNameByFileId(VfsData.java:221)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.lambda$findIndex$10(VirtualDirectoryImpl.java:783)
	at com.intellij.util.ObjectUtils.binarySearch(ObjectUtils.java:189)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findIndex(VirtualDirectoryImpl.java:783)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChildInArray(VirtualDirectoryImpl.java:101)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:120)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:83)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:532)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:51)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.findFile(PsiDirectoryImpl.java:168)
	at com.atwix.magento.project.util.MagentoModuleUtil.getModuleRegistrationFile(MagentoModuleUtil.java:137)
	at com.atwix.magento.project.util.MagentoModuleUtil.getByDir(MagentoModuleUtil.java:51)
	at com.atwix.magento.feature.module.action.NewModuleConfigFileAction.update(NewModuleConfigFileAction.kt:34)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:159)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:740)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:145)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$5(ActionUpdater.java:195)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.computeWithSpan(trace.kt:171)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:191)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:170)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:146)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:132)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:725)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:593)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$22(ActionUpdater.java:531)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1539)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:531)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:315)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:382)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:435)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:431)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$16(ActionUpdater.java:403)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/10/02
 - Plugin version: 2023.5.0/F
 - PhpStorm version: 2023.2.1 (PS-232.9559.64)
 - OS version: macOS 13.5.1

**Comment by bohdan-harniuk** [comment] 2023-10-02 16:15
Hi @mucan54 ,

I am closing this issue as duplicate of https://github.com/Atwix/phpstorm-plugin-feedback/issues/40

**Closed by bohdan-harniuk** 2023-10-02 16:15 UTC
