### ISSUE TITLE
[Bug] com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details

### ISSUE THREAD

**Issue by rsantos-dh** [Atwix/phpstorm-plugin-feedback#99] opened 2024-12-17 13:26 UTC
**Describe the bug** (*)

Just open a Magento 2 Project.

**StackTrace from IDE**

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#6759,SE-SearchTask-ControllerSEContributor,4,main] 799144369 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#75,AWT-EventQueue-0,6,main] 801773854
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:921)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:197)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTreeOrFileElement(PsiFileImpl.java:708)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:645)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:33)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:346)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getParent(StubBasedPsiElementBase.java:311)
	at com.intellij.util.xml.model.gotosymbol.GoToSymbolProvider$BaseNavigationItem.getParent(GoToSymbolProvider.java:158)
	at com.intellij.psi.impl.FakePsiElement.getManager(FakePsiElement.java:131)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider$Companion.compareElements$lambda$2(KtSearchEverywhereEqualityProvider.kt:67)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider$Companion.compareElements$reduce$lambda$0(KtSearchEverywhereEqualityProvider.kt:58)
	at kotlin.sequences.TransformingIndexedSequence$iterator$1.next(Sequences.kt:234)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:172)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider$Companion.compareElements$reduce(KtSearchEverywhereEqualityProvider.kt:60)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider$Companion.compareElements(KtSearchEverywhereEqualityProvider.kt:63)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider.compareItems(KtSearchEverywhereEqualityProvider.kt:28)
	at com.intellij.ide.actions.searcheverywhere.SEResultsEqualityProvider$Companion$composite$1.compareItems$lambda$0(SEResultsEqualityProvider.kt:74)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at com.intellij.ide.actions.searcheverywhere.SEResultsEqualityProvider$Companion$composite$1.compareItems(SEResultsEqualityProvider.kt:86)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.addElement(MixedResultsSearcher.java:322)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.processFoundItem(MixedResultsSearcher.java:222)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.lambda$run$0(MixedResultsSearcher.java:183)
	at com.atwix.magento.feature.controller.action.searcheverywhere.ControllerSEContributor.fetchWeightedElements(ControllerSEContributor.kt:77)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:182)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:206)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:74)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**To Reproduce** (*)

1. Just open a Magento 2 Project.

**Screenshots**

**System information:**

 - Occurred: 2024/12/17
 - Plugin version: 2024.3.1/L
 - IntelliJ IDEA version: 2024.3.1 (IU-243.22562.145)
 - OS version: Linux 6.8.0-50-generic

**Comment by bohdan-harniuk** [comment] 2024-12-18 14:25
Hi @rsantos-dh ,

Thank you for reporting this issue. It has been marked as a duplicate of https://github.com/Atwix/phpstorm-plugin-feedback/issues/97.

We appreciate your contribution, and the problem you've identified will be addressed within the context of the original issue. Feel free to continue monitoring the progress of the original issue.

Thank you for your understanding and your involvement in improving the project.

**Closed by bohdan-harniuk** 2024-12-18 14:25 UTC
Labels: duplicate
